name: Build and Deploy

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Deploy with rsync
        run: rsync -avz -vve.LsfxCIvu -e "ssh -vvv -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" ./public/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/public_html/